name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.0
  table_calendar: ^3.0.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add the assets section here
  assets:
    - assets/applogo.png
    - assets/attendance_svg.png
    - assets/checkin.jpg
    - assets/next.png
    - assets/company.png
